services:
  frontend-prod:
    container_name: frontend-prod
    build:
      context: .
      dockerfile: dev.dockerfile
    command: ["nginx", "-g", "daemon off;"]
    ports:
      - "127.0.0.1:1050:80"
