export const mockEventList = [
  {
    name: 'Tech Summit 2025',
    organizationName: 'InnovateTech',
    appliedCount: 120,
    confirmedCount: 90,
    visitedCount: 85,
    status: 'Actual',
  },
  {
    name: 'AI Conference',
    organizationName: 'AI World',
    appliedCount: 300,
    confirmedCount: 250,
    visitedCount: 240,
    status: 'Archived',
  },
  {
    name: 'Startup Expo',
    organizationName: 'Startup Hub',
    appliedCount: 180,
    confirmedCount: 150,
    visitedCount: 140,
    status: 'Upcoming',
  },
  {
    name: 'Blockchain Forum',
    organizationName: 'Crypto Alliance',
    appliedCount: 220,
    confirmedCount: 200,
    visitedCount: 195,
    status: 'Actual',
  },
  {
    name: 'Health & Wellness Fair',
    organizationName: 'Wellness Corp',
    appliedCount: 80,
    confirmedCount: 70,
    visitedCount: 65,
    status: 'Archived',
  },
  {
    name: 'E-commerce Workshop',
    organizationName: 'Retail Boost',
    appliedCount: 150,
    confirmedCount: 120,
    visitedCount: 110,
    status: 'Upcoming',
  },
  {
    name: 'Cybersecurity Meetup',
    organizationName: 'SecureTech',
    appliedCount: 95,
    confirmedCount: 85,
    visitedCount: 80,
    status: 'Actual',
  },
  {
    name: 'Digital Marketing Summit',
    organizationName: 'Marketing Masters',
    appliedCount: 175,
    confirmedCount: 160,
    visitedCount: 155,
    status: 'Archived',
  },
  {
    name: 'Green Energy Conference',
    organizationName: 'Eco Future',
    appliedCount: 210,
    confirmedCount: 180,
    visitedCount: 175,
    status: 'Upcoming',
  },
  {
    name: 'EdTech Symposium',
    organizationName: 'LearnNext',
    appliedCount: 130,
    confirmedCount: 110,
    visitedCount: 100,
    status: 'Actual',
  },
  {
    name: 'Finance & Investment Forum',
    organizationName: 'Wealth Builders',
    appliedCount: 190,
    confirmedCount: 160,
    visitedCount: 150,
    status: 'Upcoming',
  },
  {
    name: 'Women in Tech Conference',
    organizationName: 'TechWomen Global',
    appliedCount: 250,
    confirmedCount: 200,
    visitedCount: 195,
    status: 'Archived',
  },
  {
    name: 'Gaming Expo',
    organizationName: 'Gamer’s Paradise',
    appliedCount: 300,
    confirmedCount: 280,
    visitedCount: 275,
    status: 'Actual',
  },
  {
    name: 'Artificial Intelligence Workshop',
    organizationName: 'AI Pioneers',
    appliedCount: 125,
    confirmedCount: 100,
    visitedCount: 95,
    status: 'Upcoming',
  },
  {
    name: 'Food & Beverage Expo',
    organizationName: 'Tasty Ventures',
    appliedCount: 220,
    confirmedCount: 180,
    visitedCount: 175,
    status: 'Archived',
  },
  {
    name: 'Photography & Design Summit',
    organizationName: 'Creative Lens',
    appliedCount: 140,
    confirmedCount: 120,
    visitedCount: 110,
    status: 'Actual',
  },
  {
    name: 'Remote Work & Freelancing Meetup',
    organizationName: 'Digital Nomads',
    appliedCount: 175,
    confirmedCount: 150,
    visitedCount: 145,
    status: 'Upcoming',
  },
  {
    name: 'Space Exploration Conference',
    organizationName: 'Cosmos Research',
    appliedCount: 90,
    confirmedCount: 75,
    visitedCount: 70,
    status: 'Archived',
  },
  {
    name: 'Mental Health Awareness Event',
    organizationName: 'Mind & Wellness',
    appliedCount: 200,
    confirmedCount: 170,
    visitedCount: 165,
    status: 'Actual',
  },
  {
    name: 'Sustainable Living Expo',
    organizationName: 'GreenEarth',
    appliedCount: 150,
    confirmedCount: 130,
    visitedCount: 125,
    status: 'Upcoming',
  },
];
