export const mockEventList = [
  {
    id: '1',
    name: 'Tech Summit 2025',
    organizationName: 'InnovateTech',
    date: '21.02.2025',
    time: '10:00 - 22:00',
    dressCode: 'Business Casual',
    age: '18+',
    category: 'Technology',
    repeats: 'Annually',
    location: 'Ifithor 31, Mirzo-Ulugbeck tumani',
    description:
      'Join industry leaders and tech enthusiasts for a day of insightful discussions and networking.',
    rules:
      'Attendees must present a valid ID. No outside food or beverages allowed.',
    proposedOffersForMembers:
      'Early bird discounts, VIP access to keynote sessions, and free swag bags.',
    appliedCount: 120,
    confirmedCount: 90,
    visitedCount: 85,
    status: 'Actual',
  },
  {
    id: '2',
    name: 'AI Conference',
    organizationName: 'AI World',
    date: '15.03.2025',
    time: '09:00 - 18:00',
    dressCode: 'Formal',
    age: '21+',
    category: 'Artificial Intelligence',
    repeats: 'Bi-Annually',
    location: 'Tech Arena, Tashkent',
    description:
      'An exclusive AI event featuring top researchers, engineers, and businesses exploring the future of artificial intelligence.',
    rules:
      'All attendees must register online. Photography and recording are restricted in certain sessions.',
    proposedOffersForMembers:
      'Private networking dinner, early access to research papers, and certification of participation.',
    appliedCount: 300,
    confirmedCount: 250,
    visitedCount: 240,
    status: 'Archived',
  },
  {
    id: '3',
    name: 'Startup Expo',
    organizationName: 'Startup Hub',
    date: '10.04.2025',
    time: '18:00 - 23:00',
    dressCode: 'Smart Casual',
    age: '21+',
    category: 'Business & Networking',
    repeats: 'Quarterly',
    location: 'Tashkent Innovation Center',
    description:
      'A platform for entrepreneurs to pitch their ideas to investors and industry experts.',
    rules:
      'Pitch decks must be submitted 48 hours before the event. Each pitch is limited to 5 minutes.',
    proposedOffersForMembers:
      'Exclusive mentoring sessions, networking dinner, and investor Q&A.',
    appliedCount: 180,
    confirmedCount: 150,
    visitedCount: 140,
    status: 'Upcoming',
  },
  {
    id: '4',
    name: 'E-Commerce Forum',
    organizationName: 'Digital Trade Network',
    date: '05.05.2025',
    time: '10:00 - 16:00',
    dressCode: 'Business Formal',
    age: '18+',
    category: 'E-Commerce',
    repeats: 'Annually',
    location: 'Tashkent International Expo Center',
    description:
      'An exclusive gathering for e-commerce businesses, retailers, and logistics providers to explore the latest trends.',
    rules:
      'Participants must register in advance. Business cards are required for networking sessions.',
    proposedOffersForMembers:
      'Discounted vendor booths, priority access to workshops, and networking cocktail hour.',
    appliedCount: 220,
    confirmedCount: 180,
    visitedCount: 160,
    status: 'Upcoming',
  },
  {
    id: '5',
    name: 'Marketing Masters Conference',
    organizationName: 'Global Marketers Hub',
    date: '12.06.2025',
    time: '09:00 - 17:00',
    dressCode: 'Smart Casual',
    age: '21+',
    category: 'Marketing & Advertising',
    repeats: 'Bi-Annually',
    location: 'Grand Hotel Tashkent',
    description:
      'A deep dive into digital marketing strategies, social media trends, and brand storytelling techniques.',
    rules:
      "Recording of sessions is not allowed. Attendees must adhere to the event's code of conduct.",
    proposedOffersForMembers:
      'Access to speaker slides, free one-month premium marketing tools, and a networking lunch.',
    appliedCount: 350,
    confirmedCount: 310,
    visitedCount: 290,
    status: 'Actual',
  },
  {
    id: '6',
    name: 'FinTech Innovations Summit',
    organizationName: 'Finance Future Forum',
    date: '20.07.2025',
    time: '10:00 - 18:00',
    dressCode: 'Business Casual',
    age: '21+',
    category: 'Finance & Technology',
    repeats: 'Annually',
    location: 'Tashkent Business Center',
    description:
      'The latest insights on blockchain, digital payments, and financial automation from global experts.',
    rules:
      'Only registered guests will be allowed entry. Attendees must wear name badges at all times.',
    proposedOffersForMembers:
      'Priority seating, exclusive investor Q&A, and FinTech eBook bundle.',
    appliedCount: 280,
    confirmedCount: 230,
    visitedCount: 210,
    status: 'Actual',
  },
  {
    id: '7',
    name: 'Healthcare Tech Expo',
    organizationName: 'MedTech Innovations',
    date: '15.08.2025',
    time: '09:00 - 15:00',
    dressCode: 'Business Casual',
    age: '18+',
    category: 'Healthcare & Technology',
    repeats: 'Annually',
    location: 'UzMed Conference Hall, Tashkent',
    description:
      'A showcase of the latest medical technology, telemedicine solutions, and AI-driven healthcare innovations.',
    rules:
      'All exhibitors must submit product details for approval before the event.',
    proposedOffersForMembers:
      'Exclusive demo sessions, networking brunch, and early access to new health tech solutions.',
    appliedCount: 180,
    confirmedCount: 150,
    visitedCount: 130,
    status: 'Upcoming',
  },
  {
    id: '8',
    name: 'EdTech Global Forum',
    organizationName: 'NextGen Learning',
    date: '10.09.2025',
    time: '09:30 - 17:30',
    dressCode: 'Business Casual',
    age: '18+',
    category: 'Education & Technology',
    repeats: 'Annually',
    location: 'Tashkent Education Hub',
    description:
      'A gathering of educators, policymakers, and tech innovators to discuss the future of education and AI-driven learning.',
    rules:
      'Attendees must pre-register. No unauthorized filming of sessions is allowed.',
    proposedOffersForMembers:
      'Exclusive mentorship programs, free online courses, and early access to EdTech research reports.',
    appliedCount: 250,
    confirmedCount: 200,
    visitedCount: 180,
    status: 'Upcoming',
  },
  {
    id: '9',
    name: 'Cybersecurity Summit',
    organizationName: 'CyberShield Group',
    date: '05.10.2025',
    time: '10:00 - 16:00',
    dressCode: 'Business Formal',
    age: '21+',
    category: 'IT & Security',
    repeats: 'Bi-Annually',
    location: 'IT Park Tashkent',
    description:
      'Industry leaders discuss the latest trends in cybersecurity, ethical hacking, and data privacy regulations.',
    rules:
      'ID verification required for entry. Ethical hacking demonstrations will be conducted in a controlled environment.',
    proposedOffersForMembers:
      'Cybersecurity toolkit, access to penetration testing labs, and career networking sessions.',
    appliedCount: 320,
    confirmedCount: 280,
    visitedCount: 260,
    status: 'Actual',
  },
  {
    id: '10',
    name: 'Green Energy Expo',
    organizationName: 'EcoFuture Innovations',
    date: '15.11.2025',
    time: '09:00 - 18:00',
    dressCode: 'Casual',
    age: '18+',
    category: 'Renewable Energy & Sustainability',
    repeats: 'Annually',
    location: 'Uzbekistan Renewable Energy Center',
    description:
      'An exhibition of clean energy solutions, sustainable living technologies, and green investment opportunities.',
    rules:
      'Attendees must register in advance. Only eco-friendly materials are allowed for promotional content.',
    proposedOffersForMembers:
      'Exclusive investor meetings, discounted solar panel installations, and a guided green energy facility tour.',
    appliedCount: 200,
    confirmedCount: 170,
    visitedCount: 150,
    status: 'Upcoming',
  },
  {
    id: '11',
    name: 'Blockchain & Crypto Conference',
    organizationName: 'DeFi Global',
    date: '01.12.2025',
    time: '10:30 - 17:30',
    dressCode: 'Smart Casual',
    age: '21+',
    category: 'Blockchain & Finance',
    repeats: 'Annually',
    location: 'FinTech Tower, Tashkent',
    description:
      'An in-depth conference exploring the latest in blockchain technology, cryptocurrency regulations, and decentralized finance (DeFi).',
    rules:
      'Attendees must verify their identity for access. No financial advice will be provided during sessions.',
    proposedOffersForMembers:
      'Free crypto wallet setup, early access to blockchain courses, and networking with top blockchain developers.',
    appliedCount: 400,
    confirmedCount: 350,
    visitedCount: 320,
    status: 'Actual',
  },
];
