export const mockOrganizationList = [
  {
    name: 'Tasty Bites Cafe',
    contact: '+998901234567',
    instagram: '@tastybites_uz',
    location: 'Yunusobod 12, Tashkent',
    category: 'Restaurant',
  },
  {
    name: 'Elite Barber',
    contact: '+998939876543',
    instagram: '@elitebarber_uz',
    location: 'Yunusobod 12, Tashkent',
    category: 'Barbershop',
  },
  {
    name: 'Luxe Nails Studio',
    contact: '+998977654321',
    instagram: '@luxenails_uz',
    location: 'Yunusobod 12, Tashkent',
    category: 'Beauty Salon',
  },
  {
    name: 'SmartTech Solutions',
    contact: '+998994321098',
    instagram: '@smarttech_uz',
    location: 'Yunusobod 12, Tashkent',
    category: 'IT Services',
  },
  {
    name: 'FitPro Gym',
    contact: '+998935678901',
    instagram: '@fitprogym_uz',
    location: 'Yunusobod 12, Tashkent',
    category: 'Fitness Center',
  },
  {
    name: 'Green Market',
    contact: '+998901112233',
    instagram: '@greenmarket_uz',
    location: 'Yunusobod 12, Tashkent',
    category: 'Grocery Store',
  },
  {
    name: 'AutoFix Service',
    contact: '+998939988776',
    instagram: '@autofix_uz',
    location: 'Yunusobod 12, Tashkent',
    category: 'Car Repair',
  },
  {
    name: 'Book Haven',
    contact: '+998977711223',
    instagram: '@bookhaven_uz',
    location: 'Yunusobod 12, Tashkent',
    category: 'Bookstore',
  },
  {
    name: 'Pet Care Plus',
    contact: '+998935511223',
    instagram: '@petcareplus_uz',
    location: 'Yunusobod 12, Tashkent',
    category: 'Pet Store',
  },
  {
    name: 'Luxury Spa',
    contact: '+998998877665',
    instagram: '@luxuryspa_uz',
    location: 'Yunusobod 12, Tashkent',
    category: 'Spa & Wellness',
  },
];
