name: Deploy on Push to main
on:
  push:
    branches:
      - deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /opt/projects/frontend/dev/between-admin
            echo "pwd..."
            pwd
            ls -la
            # git remote set-url origin https://${{ secrets.GITHUB_PAT }}@github.com/Between-eMart/between-service.git
            # git fetch
            # git reset --hard origin/main

            # docker compose -f docker-compose.yml up --build -d
