export const mockInfluencerList = [
  {
    name: 'Bekzod Karimov',
    instagram: '@bek_karimov',
    followersCount: 1200,
    contact: '(+998) 91 456 78 90',
    gender: 'Male',
    location: 'Yunusobod 12, Tashkent',
    interests: ['Politics'],
    status: 'Confirm',
  },
  {
    name: 'Sardor Yuldashev',
    instagram: '@sardor_yd',
    followersCount: 1300,
    contact: '(+998) 93 987 65 43',
    gender: 'Male',
    location: 'Chilonzor 3, Tashkent',
    interests: ['Psychology'],
    status: 'Banned',
  },
  {
    name: 'Gulnora Rasulova',
    instagram: '@gulnora_r',
    followersCount: 1100,
    contact: '(+998) 95 345 67 89',
    gender: 'Female',
    location: 'Mirabad 5, Tashkent',
    interests: ['Beauty'],
    status: 'Request',
  },
  {
    name: 'Madina Akbarova',
    instagram: '@madina.akbarova',
    followersCount: 1400,
    contact: '(+998) 99 876 54 32',
    gender: 'Female',
    location: 'Shayxontoxur 8, Tashkent',
    interests: ['Fitness'],
    status: 'Confirm',
  },
  {
    name: 'Shoxrux Hamidov',
    instagram: '@shoxrux_h',
    followersCount: 1000,
    contact: '(+998) 97 234 56 78',
    gender: 'Male',
    location: 'Olmazor 14, Tashkent',
    interests: ['Gym'],
    status: 'Banned',
  },
  {
    name: 'Nodira Ismailova',
    instagram: '@nodira_ism',
    followersCount: 2200,
    contact: '(+998) 88 654 32 10',
    gender: 'Female',
    location: 'Uchtepa 7, Tashkent',
    interests: ['Photography'],
    status: 'Request',
  },
  {
    name: 'Timur Abduqahhorov',
    instagram: '@tim_abduq',
    followersCount: 3100,
    contact: '(+998) 94 321 45 67',
    gender: 'Male',
    location: 'Yakkasaroy 15, Tashkent',
    interests: ['Nature'],
    status: 'Pending',
  },
  {
    name: 'Farangiz Ergasheva',
    followersCount: 4500,
    instagram: '@farangiz.erg',
    contact: '(+998) 90 765 43 21',
    gender: 'Female',
    location: 'Sergeli 9, Tashkent',
    interests: ['Shooting'],
    status: 'Confirm',
  },
  {
    name: 'Jasur Rakhmatov',
    instagram: '@jasur_r',
    followersCount: 23560,
    contact: '(+998) 91 678 90 12',
    gender: 'Male',
    location: 'Mirobod 4, Tashkent',
    interests: ['Activity'],
    status: 'Banned',
  },
  {
    name: 'Malika Turgunova',
    instagram: '@malika_t',
    followersCount: 1200,
    contact: '(+998) 93 890 12 34',
    gender: 'Female',
    location: 'Bektemir 6, Tashkent',
    interests: ['Fashion'],
    status: 'Reject',
  },
  {
    name: 'Umid Iskandarov',
    instagram: '@umid_isk',
    followersCount: 2100,
    contact: '(+998) 95 432 10 98',
    gender: 'Male',
    location: 'Chilonzor 22, Tashkent',
    interests: ['Books'],
    status: 'Confirm',
  },
  {
    name: 'Dilrabo Abdullaeva',
    instagram: '@dilrabo.abd',
    followersCount: 2250,
    contact: '(+998) 97 210 98 76',
    gender: 'Female',
    location: 'Mirzo-Ulugbek 11, Tashkent',
    interests: ['Food'],
    status: 'Request',
  },
  {
    name: 'Rustam Alimov',
    instagram: '@rustam_al',
    followersCount: 3250,
    contact: '(+998) 99 567 89 01',
    gender: 'Male',
    location: 'Shayxontoxur 13, Tashkent',
    interests: ['Relax'],
    status: 'Banned',
  },
];
